### ISSUE TITLE
Plaigarism -> Plagiarism 

### ISSUE THREAD

**Issue by mac-chaffee** [mdaum/PlaigarismCoupler#3]
The correct spelling is "plagiarism". 

Would it be a simple find-and-replace to fix this or is it more complicated than that?

**Comment by mdaum** [comment]
Slightly more complicated since I have to notify other ppls projects who use this library but shouldn't be an issue....will sync up with advisor and let him know of change after I make it. Thanks good catch. English is hard

**Comment by mdaum** [comment]
Update: this is on my to-do....slammed with other projects/presentations ATM but should get to this within 7 days....if you intend on sharing this with nc state prof please CC me at mdaum@cs.unc.edu and my advisor dewan@cs.unc.edu

**Comment by mdaum** [comment]
CC if you send a forward of this repo. We are happy to give overview and/or help integrate 😀
